# NumPy
## Phase # 1

### Arrays


In [ ]:
import numpy as np
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d)


arr_2d = np.array([[1,3,4,5], [1,3,5,6]])
print(arr_2d)




[1 2 3 4 5 6]
[[1 3 4 5]
 [1 3 5 6]]


In [ ]:
py_list = [1, 3, 5]
print(py_list * 2)

np_array = np.array([1,3,5])
print("Num array mul: ", np_array * 2) # here 2 is called scaler , in term of DS


[1, 3, 5, 1, 3, 5]
Num array mul:  [ 2  6 10]


In [ ]:
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:", time.time() - start)

start = time.time()
np_array = np.arange(1000000)
print("\n Numpy operation time:", time.time() - start) # numpy is too fast then py list


 List operation time: 0.08052706718444824

 Numpy operation time: 0.0019545555114746094


In [ ]:
zeros = np.zeros([3, 3])
print('zeros array:\n', zeros)

once = np.ones((2,3))
print('once array:\n', once)

full = np.full((2,3), 7)
print('full array:\n', full)

random = np.random.random((2,4))
print('random array:\n', random)

sequence = np.arange(0, 11, 2) # range 0 to 10, and in b/w skip 1 if you give 2 like this np.arange(0, 11, 2)
print('sequence array:\n', sequence)

zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
once array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7 7]
 [7 7 7]]
random array:
 [[0.35632503 0.89001508 0.25595599 0.99827046]
 [0.73814394 0.22676442 0.8978267  0.40740933]]
sequence array:
 [ 0  2  4  6  8 10]


### Vector, Matrix & Tensor


In [13]:
vector = np.array([1,3,4])
print(vector)

matrix = np.array([[2,3,5], [5,6,7]])
print(matrix)

tensor = np.array([[[1,3], [3,5]],
                [[5,3], [9,5]]])
print(tensor) # multi dimensional array is actual tensor


[1 3 4]
[[2 3 5]
 [5 6 7]]
[[[1 3]
  [3 5]]

 [[5 3]
  [9 5]]]


### Array properties

In [14]:
arr = np.array([1,3,4])

print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size/Length: ", arr.size)
print("Data types: ", arr.dtype)

Shape:  (3,)
Dimension:  1
Size/Length:  3
Data types:  int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array", reshaped)

flattened = reshaped.flatten()
print("\n Flattened " , flattened)

# ravel return view, instead of copy
raveled = reshaped.ravel()
print("\n Reveled " , raveled)

transpose = reshaped.T
print("\n Transpose " ,transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reveled  [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Phase # 2


### Indexing & Slicing

In [10]:
import numpy as np

arrx = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:", arrx[0])
print("Basic Slicing:", arrx[1:5])
print("With Step:", arrx[1:8:2])
print("Negative Indexing:", arrx[-3])


Basic Slicing: 1
Basic Slicing: [2 3 4 5]
With Step: [2 4 6 8]
Negative Indexing: 8


In [13]:
arr_2d = np.array([[2,3,4], [5,6,7], [8,9,9]])
print("Specific element", arr_2d[1,2])
print("Entire row", arr_2d[1])
print("Entire column", arr_2d[:,1])

Specific element 7
Entire row [5 6 7]
Entire column [3 6 9]


#### Sorting array

In [20]:
unsorted = np.array([3,6,2,0, 8, 33, 22])
print("Sorted Array", np.sort(unsorted))

unsorted_arr_2d = np.array([[3,1], [1,2], [2,3]])
print("Sorted 2D Array by column: \n", np.sort(unsorted_arr_2d, axis=0)) #mostly used axis=0 sort by column (top to bottom)
print("Sorted 2D Array by row: \n", np.sort(unsorted_arr_2d, axis=1))

Sorted Array [ 0  2  3  6  8 22 33]
Sorted 2D Array by column: 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D Array by row: 
 [[1 3]
 [1 2]
 [2 3]]


### Filtering array

In [ ]:
numbers = np.array([3,6,2,0, 8, 33, 22])
even_num = numbers[numbers % 2 == 0] 
print("Even Numbers", even_num)

# Filter with mask (evaluated expression)
mask = numbers % 2 == 0
print("Numbers greated than 5: ", numbers[mask])


Even Numbers [ 6  2  0  8 22]
Numbers greated than 5:  [ 6  2  0  8 22]


### Fancy Indexing vs np.where()

In [35]:
indices = [0, 2, 4]
numbers = np.array([3,6,2,0, 8, 33, 22])
print(numbers[indices])

where_result = np.where(numbers > 5) # store filter elements index
print("NumPy Where: ", numbers[where_result], where_result)


condition_array = np.where(numbers > 5, numbers * 4, numbers) # not clear
print(condition_array)

# CONDITION ARRAY HOW ACTUALLY WORK LIKE BELOW 
# if(numbers > 5):
#     numbers* 4
# else
#     numbers

condition_array2 = np.where(numbers > 5, "true", "false")
print(condition_array2)


[3 2 8]
NumPy Where:  [ 6  8 33 22] (array([1, 4, 5, 6]),)
[  3  24   2   0  32 132  88]
['false' 'true' 'false' 'false' 'true' 'true' 'true']


### Adding and removing Data

In [10]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print("Addition: ", arr1 + arr2)

combine = np.concatenate((arr1, arr2))
print("Combined Array: ", combine)


arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2) # delete index 2
print("Deleted Array: ", deleted)

Addition:  [ 7  9 11 13 15]
Combined Array:  [ 1  2  3  4  5  6  7  8  9 10]
Deleted Array:  [1 2 4 5]


### Array compatibility

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,4 ,6])
c = np.array([7,8,9])

print("Array Compatibility Shapes:", a.shape == b.shape)

original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
with_new_row = np.vstack((original, new_row)) # v stack is used to stack arrays in sequence vertically (row wise) or add new row 
with_new_column = np.hstack((original, new_row.T)) # h stack is used to stack arrays in sequence horizontally (column wise) or add new column
print("Original Array:\n", original)
print("Array with new row:\n", with_new_row)
print("Array with new column:\n", with_new_column)

Array Compatibility Shapes: False
Original Array:
 [[1 2]
 [3 4]]
Array with new row:
 [[1 2]
 [3 4]
 [5 6]]
Array with new column:
 [[1 2 5]
 [3 4 6]]


## Phase # 3

### Advance operation with Business examples

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], # Paradise Biryani
    [2, 120000, 140000, 160000, 190000], # Beijing Bites
    [3, 200000, 230000, 260000, 300000], # Pizza Hub
    [4, 180000, 210000, 240000, 270000], # Burger Point
    [5, 160000, 185000, 265000, 230000]  # Chai Point
])


print("Sales Analysis\n")

print("\n Sales data shape: ", sales_data.shape)

print("\n Sample data (first 2 rows):\n", sales_data[:3])

# Total sales for each restaurant over the years
total_sales = np.sum(sales_data[:, 1:], axis=1)
print("\n Total sales for each restaurant:\n", total_sales)
sum_of_all_sales = np.sum(total_sales)
print("\n Sum of all sales: ", sum_of_all_sales)


# Total sales each year across all restaurants
yearly_sales = np.sum(sales_data[:, 1:], axis=0)
print("\n Total sales each year:\n", yearly_sales)




Sales Analysis


 Sales data shape:  (5, 5)

 Sample data (first 2 rows):
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

 Total sales for each restaurant:
 [800000 610000 990000 900000 840000]

 Sum of all sales:  4140000

 Total sales each year:
 [ 810000  945000 1145000 1240000]

 Maximum sales for each restaurant:
 [250000 190000 300000 270000 265000]

 Minimum sales for each restaurant:
 [150000 120000 200000 180000 160000]

 Average sales for each restaurant:
 [200000. 152500. 247500. 225000. 210000.]

 Cumulative sales for each restaurant over the years:
 [[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 610000 840000]]


In [27]:
# Maximum sales for each restaurant over the years
max_sales = np.max(sales_data[:, 1:], axis=1)
print("\n Maximum sales for each restaurant:\n", max_sales)

# Minimum sales for each restaurant over the years
min_sales = np.min(sales_data[:, 1:], axis=1)
print("\n Minimum sales for each restaurant:\n", min_sales)

# Average sales for each restaurant over the years
avg_sales = np.mean(sales_data[:, 1:], axis=1)
print("\n Average sales for each restaurant:\n", avg_sales)

# Sales cummulative sum for each restaurant over the years
cumsum_sales = np.cumsum(sales_data[:, 1:], axis=1)
print("\n Cumulative sales for each restaurant over the years:\n", cumsum_sales)


 Maximum sales for each restaurant:
 [250000 190000 300000 270000 265000]

 Minimum sales for each restaurant:
 [150000 120000 200000 180000 160000]

 Average sales for each restaurant:
 [200000. 152500. 247500. 225000. 210000.]

 Cumulative sales for each restaurant over the years:
 [[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 610000 840000]]


### vector operation


In [29]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

# dot product of two matrix
dot_product = np.dot(vector1, vector2)
print("Dot Product: ", dot_product)

# multiplication of two matrix
print("Multiplication: ", vector1 * vector2)

# angle between two vectors
magnitude_v1 = np.linalg.norm(vector1)
magnitude_v2 = np.linalg.norm(vector2)
cosine_angle = dot_product / (magnitude_v1 * magnitude_v2)
angle = np.arccos(cosine_angle)
print("Angle between vectors (radians): ", angle)
print("Angle between vectors (degrees): ", np.degrees(angle))

Dot Product:  32
Multiplication:  [ 4 10 18]
Angle between vectors (radians):  0.2257261285527342
Angle between vectors (degrees):  12.933154491899135


### vectorization operation

In [32]:
# this is help to perform operation on each element of list/array once we make it vectorized

res_data = np.array(["biryani", "burger", "pizza", "chai", "beijing"])
vectorized_upper_func = np.vectorize(str.upper)

print("Vectorized Upper Case:\n", vectorized_upper_func(res_data))

Vectorized Upper Case:
 ['BIRYANI' 'BURGER' 'PIZZA' 'CHAI' 'BEIJING']
